use_frameworks!

target 'DataProvider_Example' do
  pod 'DataProvider', :path => '../'

  target 'DataProvider_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
