source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

target 'DataProvider_Example' do
  pod 'DataProvider', :path => '../'

  target 'DataProvider_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
